### ISSUE TITLE
Providing native build inputs

### ISSUE THREAD

**Issue by rycee** [nmattia/naersk#50]
It would be nice if it was possible to add an `nativeBuildInputs` attribute to `buildPackage`. E.g. in a project of mine I'd like to have
```nix
naersk.buildPackage {
  root = ./.;
  buildInputs = with pkgs; [ dbus ];
  nativeBuildInputs = with pkgs; [ pkgconfig rustfmt ];
}
```

**Comment by nmattia** [comment]
I think this was fixed by https://github.com/nmattia/naersk/pull/75. can you confirm?

**Comment by Gerschtli** [comment]
Follow-Up to https://github.com/nmattia/naersk/issues/50 as this issue got closed:

> It would be nice if it was possible to add an nativeBuildInputs attribute to buildPackage. E.g. in a project of mine I'd like to have
>
> ```nix
> naersk.buildPackage {
>   root = ./.;
>   buildInputs = with pkgs; [ dbus ];
>   nativeBuildInputs = with pkgs; [ pkgconfig rustfmt ];
> }
> ```

Unfortunately this does not fix it like you would expect it. If you set `nativeBuildInputs` this will override the default inputs declared in https://github.com/nmattia/naersk/blob/master/build.nix#L179-L184.

I think the `nativeBuildInputs` should be handled like the `buildInputs` and just add new packages instead of overriding.

I'll try to create a PR for that.

**Comment by nmattia** [comment]
That's right, overlooked that! Thanks for the fix!
